---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "network.name" . }}-composer-rest-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "network.name" . }}-composer-rest-server
      labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}  
        component: composer-rest-server
    spec:
      volumes:
      - name: {{ template "network.name" . }}-shared-pvc
        persistentVolumeClaim:
          claimName: {{ template "network.name" . }}-shared-pvc
      - name: {{ template "network.name" . }}-composer-pvc
        persistentVolumeClaim:
          claimName: {{ template "network.name" . }}-composer-pvc
      initContainers:
      - name: await-network-install-org1peer1
        image: busybox:1.28.4
        command:
        - sh
        - -c
        - |
          while [ ! -f /shared/status_chaincode_install_org1peer1_complete ]; do
            echo Waiting for Chaincode install to complete on org1peer1
            sleep 5s
          done
          echo Chaincode installed on org1peer1
        volumeMounts:
        - mountPath: /shared
          name: {{ template "network.name" . }}-shared-pvc
      containers:
      - name: composer-rest-server
        image: {{ .Values.composer.restServerImage }}
        imagePullPolicy: {{ .Values.composer.pullPolicy }}
        env:
        - name: COMPOSER_CARD
          value: experience-admin.card
        - name: COMPOSER_NAMESPACES
          value: never
        volumeMounts:
        - name: {{ template "network.name" . }}-composer-pvc
          mountPath: /home/composer/.composer
...
---
# The service to expose composer rest server
apiVersion: v1
kind: Service
metadata:
  name: {{ template "network.name" . }}-composer-rest-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
    component: composer-rest-server
  ports:
  - protocol: TCP
    port: 3000
    #nodePort: 31090
    name: http
...