---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "network.name" . }}-createchannel
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: createchannel 
spec:
  restartPolicy: "Never"
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc
  initContainers:
  - name: init-service
    image: busybox:1.28.4
    command:
    - sh
    - -c
    - |
      while [ ! -f /shared/status_bootstrapping_complete ]; do
        echo Waiting for bootstrapping to complete
        sleep 5s
      done
      echo bootstrapping completed
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
  containers:
  - name: createchanneltx
    image: {{ .Values.fabric.toolsImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command:
    - sh
    - -c
    - |
      cd /shared
      configtxgen -profile TwoOrgsChannel -outputCreateChannelTx ${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME}
      touch /shared/status_channeltx_complete # && rm /shared/status_bootstrapping_complete
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: FABRIC_CFG_PATH
      value: /shared
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
  - name: createchannel
    image: {{ .Values.fabric.peerImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command: 
    - sh
    - -c
    - |
      while [ ! -f /shared/status_channeltx_complete ]
      do
        echo Waiting for channeltx
        sleep 5s
      done
      peer channel create --orderer ${ORDERER_URL} --channelID ${CHANNEL_NAME} --file /shared/${CHANNEL_NAME}.tx
      rm /shared/status_channeltx_complete
      touch /shared/status_channelcreate_complete
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: ORDERER_URL
      value: {{ template "network.name" . }}-orderer:31010
    - name: CORE_PEER_ADDRESSAUTODETECT
      value: "false"
    - name: CORE_PEER_NETWORKID
      value: nid1
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
    - name: CORE_LOGGING_LEVEL
      value: debug
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
