---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "network.name" . }}-org1peer1-joinchannel
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: org1peer1-joinchannel
spec:
  restartPolicy: Never
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc
  initContainers:
  - name: await-orderer
    image: busybox:1.28.4
    command:
    - sh
    - -c
    - |
      while [ ! -f /shared/status_orderer_complete ]; do
        echo Waiting for Orderer to complete
        sleep 5s
      done
      echo Orderer completed
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
  containers:
  - name: joinchannel
    image: {{ .Values.fabric.peerImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command: 
    - sh
    - -c
    - |
      echo Sleeping for 120s hoping to awake once the Orderer and Channel are ready
      sleep 120s

      while [ ! -f /shared/status_channelcreate_complete ];
      do
        echo Waiting for Create Channel to complete
        sleep 5s
      done
      echo Create Channel completed

      #peer channel fetch config --orderer ${ORDERER_URL} --channelID ${CHANNEL_NAME}
      cd /shared
      peer channel join --blockpath ${CHANNEL_NAME}.block
      touch /shared/status_joinchannel_org1peer1_complete
      echo org1peer1 joined channel
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: CORE_PEER_NETWORKID
      value: nid1
    - name: ORDERER_URL
      value: {{ template "network.name" . }}-orderer:31010
    - name: CORE_PEER_ADDRESS
      value: {{ template "network.name" . }}-org1peer1:30110
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: FABRIC_LOGGING_SPEC
      value: warning
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
...
