---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "network.name" . }}-org1peer1-network-install
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: org1peer1-network-install
spec:
  restartPolicy: Never
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
      defaultMode: 256
  initContainers:
  - name: await-joinchannel-org1peer1
    image: busybox:1.28.4
    command:
    - sh
    - -c
    - |
      while [ ! -f /shared/status_joinchannel_org1peer1_complete ]; do
        echo Waiting for org1peer1 to join
        sleep 5s
      done
      echo org1peer1 has joined
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
  containers:
  - name: network-install
    image: {{ .Values.fabric.toolsImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command:
    - sh
    - -c
    - |
      cat /secret-volume/ssh-privatekey
      GIT_SSH_COMMAND="ssh -oStrictHostKeyChecking=no -i /secret-volume/ssh-privatekey" git clone -b master ssh://git@innersource.accenture.com/a630/fy19_dlt.git
    
      BN=experience
      BNA_FILE="$BN.bna"
      BN_ADMIN_CARD="$BN-admin.card"
      PEER_ADMIN=PeerAdmin@hlfv1
      BN_ADMIN_USER=admin
      BN_ADMIN_PWD=adminpw
      BN_VERSION=0.0.0

      composer archive create -a $BNA_FILE --sourceType dir --sourceName .
      BN_VERSION=$(composer archive list -a $BNA_FILE | grep "Version" | cut -d':' -f 2)
      composer network install --archiveFile $BNA_FILE --card PeerAdmin@hlfv1
      composer network start --networkName $BN --networkVersion $BN_VERSION --networkAdmin $BN_ADMIN_USER --networkAdminEnrollSecret $BN_ADMIN_PWD --card $PEER_ADMIN --file $BN_ADMIN_CARD
      composer card import --file $BN_ADMIN_CARD --card $BN_ADMIN_USER@$BN

      touch /shared/status_chaincode_install_org1peer1_complete
    env:
    - name: CHAINCODE_NAME
      value: {{ .Values.chaincode.name }}
    - name: CHAINCODE_VERSION
      value: {{ .Values.chaincode.version }}
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_ADDRESS
      value: {{ template "network.name" . }}-org1peer1:30110
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
    - name: secret-volume
      mountPath: "/secret-volume"
